tasks:
  - name: remove-label
    on:
      issue_comment:
        types: [created]
    config:
      label: "needs reply"
      exclude-labeler: true
  - name: add-contributors
    on:
      push:
        branches: [main]
    config:
      base: main
      commitMsg: "chore(readme): add a new contributor"
